### ISSUE TITLE
br は文章の改行のため以外に使ってはいけない

### ISSUE THREAD

**Issue by kintsuba** [Leies-202/leies-me#6]
https://github.com/Leies-202/leies-me/blob/9819663699b4e26dfc9add896c7fc7082a06d7ce/index.html#L192

参考: https://developer.mozilla.org/ja/docs/Web/HTML/Element/br

**Comment by Leies-202** [comment]
Done
https://github.com/Leies-202/leies-me/commit/f5b53c026bb4f8f6673a04bc6b6cd8a73f2161c5
